const productos = [
    {id: 1, nombre: "Agenda de viaje", descripcion: "Tener una agenda de viaje es invaluable. Te permite organizar tus actividades, maximizar tu tiempo y evitar olvidos. Puede planificar visitas a lugares turísticos, reservar alojamiento y gestionar transportes sin estrés. Además, te brinda una visión general de tu itinerario, permitiéndote disfrutar al máximo cada momento y crear recuerdos inolvidables.", categoria: "Producto", pais: "Argentina", precio: 1000, imgUrl: "https://dondemellevelviento.com/wp-content/uploads/2021/10/Agenda-anillos-dorados-Perseguir-tus-suen%CC%83os.jpg"},
    {id: 2, nombre: "Calendario de fotos", descripcion: "Tener un calendario con fotos personales es maravilloso. Cada mes te brinda un recordatorio visual de tus momentos especiales y seres queridos. Te ayuda a mantenerte organizado y apreciar el paso del tiempo. Además, es un regalo perfecto para compartir tus recuerdos con familiares y amigos durante todo el año.", categoria: "Producto", pais: "Argentina", precio: 1500, imgUrl: "https://img.elo7.com.br/product/zoom/33F0E36/foto-polaroid-calendario-fotopolaroidcalendario.jpg"},
    {id: 3, nombre: "Community Manager", descripcion: "Contar con un community manager para tu negocio es esencial. Me encargo de gestionar tus redes sociales, interactuar con tu audiencia y crear una imagen positiva de tu marca. Mi experiencia en estrategias de marketing digital y capacidad para generar contenido relevante te ayudará a aumentar tu visibilidad, atraer clientes y fidelizarlos.", categoria: "Servicio", pais: "Internacional", precio: 2000, imgUrl: "https://images.milanuncios.com/api/v1/ma-ad-media-pro/images/a0713b6f-6420-4a1e-9c2e-b7bfeb05d725?rule=detail_640x480"},
    {id: 4, nombre: "Drone y Fotografia", descripcion: "Contratar un piloto de dron y un fotógrafo es una combinación ganadora. Obtendrá imágenes y vídeos aéreos de alta calidad para destacar su negocio, capturar momentos especiales o documentar eventos. El piloto de dron proporciona perspectivas únicas, mientras que el fotógrafo asegura tomas profesionales. Juntos, te brindarán un contenido visual impactante y versátil.", categoria: "Servicio", pais: "Internacional", precio: 2500, imgUrl: "https://upload.wikimedia.org/wikipedia/commons/c/ca/Autumn_Drone_%28cropped%29.jpg"},
    {id: 5, nombre: "Bitacoras de viaje", descripcion: "Tener una bitácora de viaje es una forma fantástica de capturar tus aventuras. Puedes plasmar tus experiencias, emociones y descubrimientos en papel o digitalmente. Además, te permite revivir tus recuerdos y compartirlos con otros. Una bitácora de viaje es un tesoro personal que te conecta con tus viajes de manera única.", categoria: "Producto", pais: "Internacional", precio: 3000, imgUrl: "https://www.tematika.com/media/catalog/Ilhsa/Imagenes/677939.jpg"},
    {id: 6, nombre: "Stickers viajeros", descripcion: "Tener stickers viajeros es una forma divertida de capturar tus aventuras. Puedes pegarlos en tu equipaje, portátil o cuaderno, mostrando orgullosamente los lugares que has visitado. Los stickers son pequeños tesoros visuales que te permiten revivir tus viajes y compartir tus experiencias con estilo y originalidad.", categoria: "Producto", pais: "Argentina", precio: 3500, imgUrl: "https://http2.mlstatic.com/D_NQ_NP_728295-MLA53318658022_012023-W.jpg"},
    {id: 7, nombre: "Diseño de Pagina WEB", descripcion: "Tener una página web para tu negocio es fundamental en la era digital. Te brinda una presencia en línea las 24 horas, con visibilidad y certeza. Puedes mostrar tus productos, servicios y testimonios, alcanzando un público global. Además, una web bien diseñada facilita la comunicación, captación de clientes y aumenta tus oportunidades de crecimiento.", categoria: "Servicio", pais: "Internacional", precio: 20000, imgUrl: "https://webcion.com/wp-content/uploads/2021/11/pngwing.com-1.png"},
    {id: 8, nombre: "Asistente Virtual", descripcion: "Contar con una asistente virtual es una bendición moderna. Puedes delegar tareas, programar recordatorios y recibir información en tiempo real. Tu asistente virtual está disponible las 24 horas, lo que facilita la gestión de tu agenda y aumenta tu productividad. Además, te brinda comodidad y libertad para enfocarte en lo importante.", categoria: "Servicio", pais: "Internacional", precio: 2000, imgUrl: "https://escuelanomadadigital.com/wp-content/uploads/2020/02/como-ser-asistente-virtual.jpg"},
    {id: 9, nombre: "Bolso de Viaje", descripcion: "Tener un bolso de viaje es una inversión inteligente. Te proporciona comodidad y practicidad durante tus desplazamientos. Puedes organizar tus pertenencias de manera eficiente y tener todo a mano. Además, su diseño resistente y duradero asegura que tus cosas estén protegidas. Un bolso de viaje es tu compañero ideal para explorar el mundo con estilo.a", categoria: "Producto", pais: "Argentina", precio: 1500, imgUrl: "https://scontent.fmdz1-1.fna.fbcdn.net/v/t1.6435-9/47386343_307012239913641_4796561159106854912_n.jpg?stp=cp0_dst-jpg_e15_p320x320_q65&_nc_cat=109&ccb=1-7&_nc_sid=2d5d41&_nc_ohc=6osWF_7NAVcAX8U1p8T&_nc_ht=scontent.fmdz1-1.fna&oh=00_AfBcJMKiVugHVGy4j9qmqZAO4yn1TL7oXIEfGLo-Em-UyQ&oe=64CE3549"},
    {id: 10, nombre: "Manta viajera", descripcion: "Tener una manta de viaje es una decisión inteligente. Te brinda comodidad y calidez en cualquier lugar al que vayas. Puedes usarla en aviones, trenes o durante actividades al aire libre. Además, su diseño compacto y ligero la hace fácil de transportar. Una manta de viaje es tu aliada perfecta para sentirte como en casa estés donde estés.", categoria: "Producto", pais: "Argentina", precio: 1500, imgUrl: "https://d3ugyf2ht6aenh.cloudfront.net/stores/878/653/products/20210410_1658081-41d1e9a182dd3a65a316180886424308-240-0.jpg"},
    {id: 11, nombre: "Armado de itinerario", descripcion: "Contar con un itinerario de viaje armado por expertos es una garantía de disfrute sin preocupaciones. Ahorrarás tiempo y estrés al tener todas las reservas y actividades planificadas. Además, te asegurarás de no perderte los lugares y experiencias más destacados, optimizando tu tiempo y maximizando la diversión en cada destino.", categoria: "Servicio", pais: "Internacional", precio: 2000, imgUrl: "https://img.freepik.com/fotos-premium/fondo-mapa-accesorios-viaje-vacaciones-vista-superior-vertical_771335-11736.jpg?w=740"},
    {id: 12, nombre: "Viajemos en grupo!", descripcion: "Viajar en grupo ofrece innumerables beneficios. Compartir experiencias con amigos o familia crea recuerdos inolvidables. Puedes dividir gastos y obtener mejores tarifas en alojamiento y transporte. Además, la compañía brinda seguridad y diversión durante el viaje, y juntos descubren destinos de manera más enriquecedora, compartiendo momentos de alegría y complicidad.", categoria: "Servicio", pais: "Argentina", precio: 50000, imgUrl: "https://img.freepik.com/fotos-premium/amigos-multirraciales-sonrientes-toman-selfie-mirando-camara-copia-espacio-imagen-vertical-amistad-concepto-redes-sociales_411082-992.jpg?w=740"}
];
  
guardarProductosLS();

